### ISSUE TITLE
Macos puerts-webgl install button error

### ISSUE THREAD

**Issue by orangeagain** [zombieyang/puerts_unity_webgl_demo#19]
## error log | 日志或报错信息
```
Exception: child_process.js:655: Error: Command failed: npm i
/bin/sh: npm: command not found


Error: Command failed: npm i
/bin/sh: npm: command not found

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at chunk:3:42
Puerts.GenericDelegate.Action[T1] (T1 p1) (at Library/PackageCache/com.tencent.puerts.core@3066baced2/Runtime/Src/GenericDelegate.cs:503)
WebGLPuertsPostProcessor.npmInstall () (at /Users/elonwu/Downloads/puerts_unity_webgl_demo-master/package/Editor/WebGLPostProcessor.cs:77)
```

## context | 编译/运行环境
MacOs M1 机器
Unity 版本 2021.3.1f1c1 Rossta 兼容版本

## how to reproduce | 复现步骤
1.打开Rotate项目的例子
2. 点菜单栏里的 puerts-webgl=》install
3.console里出错

## more | 其他
可能是调用 Macos 系统命令不兼容的原因，因为在终端中运行命令就可以
```
~ % npm i

up to date in 2s

1 package is looking for funding
  run `npm fund` for details
```

**Comment by zombieyang** [comment]
根据群友反馈这个方式可以结局
https://support.unity.com/hc/en-us/articles/360044824951-I-need-to-start-Unity-with-an-environment-variable-s-set-how-can-I-do-that

------
后续版本考虑将childprocess调用去掉
